// Users

// Movies
export const DISPLAY_MOVIES = 'DISPLAY_MOVIES';

export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

// Schedules

export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';

// Reservations

export const ADD_RESERVATION_SUCCESS = 'ADD_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';


// Search

export const LOAD_SEARCH = 'LOAD_SEARCH';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';