// Users
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_LOGIN = "GET_USER_BY_LOGIN";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER_BY_ID = "UPDATE_USER_BY_ID";
export const UPDATE_USER_BY_LOGIN = "UPDATE_USER_BY_LOGIN";
export const DELETE_USER_BY_ID = "DELETE_USER_BY_ID";
export const DELETE_USER_BY_LOGIN = "DELETE_USER_BY_LOGIN";

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

// Movies
export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_BY_NAME = "GET_MOVIE_BY_NAME";
export const ADD_MOVIE = 'ADD_MOVIE';
export const UPDATE_MOVIE_BY_ID = "UPDATE_MOVIE_BY_ID";
export const REMOVE_MOVIE = 'REMOVE_MOVIE';

export const DISPLAY_MOVIES = "DISPLAY_MOVIES";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const REMOVE_MOVIE_SUCCESS = "REMOVE_MOVIE_SUCCESS";
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

//-----

// Schedules

export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';

export const INCREMENT_SEANCE_PLACES = 'INCREMENT_SEANCE_PLACES';
export const DECREMENT_SEANCE_PLACES = 'DECREMENT_SEANCE_PLACES';

// Reservations

export const DISPLAY_RESERVATIONS = 'DISPLAY_RESERVATIONS';
export const ADD_RESERVATION_SUCCESS = 'ADD_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';

// Room

export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';


// Search

export const LOAD_SEARCH = 'LOAD_SEARCH';